version: "3.9"

services:
  postgres:
    image: ankane/pgvector:latest
    container_name: quantleaves-postgres
    environment:
      POSTGRES_DB: quantleaves
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
