openapi: 3.1.0
info:
  title: QuantLeaves Metrics API
  version: 1.0.0
servers:
  - url: https://api.quantleaves.com
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
security:
  - bearerAuth: []
paths:
  /v1/metrics:
    get:
      summary: List or query metrics
      description: Returns metric values when metric_id and time range are provided; otherwise lists available metrics.
      parameters:
        - name: metric_id
          in: query
          required: false
          schema: { type: string }
        - name: from
          in: query
          required: false
          schema: { type: string, format: date-time }
        - name: to
          in: query
          required: false
          schema: { type: string, format: date-time }
      responses:
        "200":
          description: OK
        "401":
          description: E1001 Auth token missing
        "429":
          description: E1002 Rate limit exceeded
  /v1/dimensions:
    get:
      summary: List available dimensions
      responses:
        "200":
          description: OK
x-rate-limits:
  Starter: "60/min"
  Pro: "600/min"
  Enterprise: "2000/min"
